apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: balance-details
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 3600000 # 1 hour