apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        overrides:
          brokers:
            - broker: 0
              advertisedHost: my-cluster-kafka-a448854c607b0cca.elb.ap-south-1.amazonaws.com
              advertisedPort: 19092
    # This configuration enables network load balancer for each broker. 
    # template:
    #   externalBootstrapService:
    #     metadata: 
    #       annotations:
    #         service.beta.kubernetes.io/aws-load-balancer-type: nlb
    #   perPodService:
    #     metadata:
    #       annotations:
    #         service.beta.kubernetes.io/aws-load-balancer-type: nlb
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
