apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  selector:
    matchLabels:
      app: kafka-producer
      type: queue
  template:
    metadata:
      labels:
        app: kafka-producer
        type: queue
    spec:
      containers:
      - name: kafka-producer
        image: vaibhavsatam/kafka_producer
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
